In [1]:
import pandas as pd

In [27]:
def findMaximals(df):
    embDict = {}
    for _, row in df.iterrows():
        emb = row['Embedding']
        basis = row['Basis']
        newAcc = row['New Acc']
        oldAcc = row['Old Acc']
        iteration = row['Iteration Num']
        if emb not in embDict:
            embDict[emb] = {'maxNewAcc': newAcc, 'maxRow': row, 'oldAcc': -1}
        else:
            if newAcc > embDict[emb]['maxNewAcc'] or (newAcc == embDict[emb]['maxNewAcc'] and 'class' in basis):
                embDict[emb] = {'maxNewAcc': newAcc, 'maxRow': row, 'oldAcc': embDict[emb]['oldAcc']}
        if iteration == 1:
            embDict[emb]['oldAcc'] = oldAcc
    finalRows = []
    for emb in embDict:
        finalRows.append([*embDict[emb]['maxRow'].to_list(), embDict[emb]['oldAcc'], embDict[emb]['maxRow']['New Acc'] - embDict[emb]['oldAcc']])
    return pd.DataFrame(finalRows)

In [16]:
unsupSumm = pd.read_csv('../data/retrofitting/retro_test_Sept_21_2021.csv')
findMaximals(unsupSumm)

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,text_7_props,19k_childPar,2,True,1,57.267442,57.267442,0.000000,344,0.325000,...,0.333333,0.75,0.461538,0.210526,0.038835,0.065574,12.082148,0,57.267442,0.000000
1,text_2_props,19k_2_class,2,True,1,56.686047,56.104651,-0.581395,344,0.292683,...,0.288889,0.65,0.400000,0.210526,0.038835,0.065574,87.920485,0,56.686047,-0.581395
2,complex,19k_childPar,1,True,3,67.151163,68.023256,0.872093,344,0.916667,...,0.923077,0.60,0.727273,0.505747,0.427184,0.463158,18.160508,0,60.174419,7.848837
3,transe,19k_class_childPar,1,True,1,63.662791,67.732558,4.069767,344,0.900000,...,0.812500,0.65,0.722222,0.511628,0.213592,0.301370,3.838469,0,63.662791,4.069767
4,abstract,19k_class_childPar,2,True,1,63.953488,64.244186,0.290698,344,0.461538,...,0.468750,0.75,0.576923,0.666667,0.038835,0.073394,4.033524,0,63.953488,0.290698
5,abstract_first_sent,19k_class_siblings,2,True,1,65.697674,65.697674,0.000000,344,0.500000,...,0.520000,0.65,0.577778,0.700000,0.067961,0.123894,19.390705,0,65.697674,0.000000

In [45]:
def findPrecRecIMaximals(df):
    embDict = {}
    for _, row in df.iterrows():
        emb = row['Embedding']
        basis = row['Basis']
        newAcc = row['New I F1-Score']
        oldAcc = row['Old I F1-Score']
        iteration = row['Iteration Num']
        if emb not in embDict:
            embDict[emb] = {'maxNewAcc': newAcc, 'maxRow': row, 'oldAcc': -1}
        else:
            if newAcc > embDict[emb]['maxNewAcc'] or (newAcc == embDict[emb]['maxNewAcc'] and 'class' in basis):
                embDict[emb] = {'maxNewAcc': newAcc, 'maxRow': row, 'oldAcc': embDict[emb]['oldAcc']}
        if iteration == 1:
            embDict[emb]['oldAcc'] = oldAcc
    finalRows = []
    for emb in embDict:
        finalRows.append([*embDict[emb]['maxRow'].to_list()[:5], embDict[emb]['oldAcc'], embDict[emb]['maxRow']['New I F1-Score'], embDict[emb]['maxRow']['New I F1-Score'] - embDict[emb]['oldAcc'], embDict[emb]['maxRow']['Old I Precision'], embDict[emb]['maxRow']['New I Precision'], embDict[emb]['maxRow']['Old I Recall'], embDict[emb]['maxRow']['New I Recall'], ])
    return pd.DataFrame(finalRows)

In [46]:
unsupSumm = pd.read_csv('../data/retrofitting/retro_test_Sept_21_2021.csv')
findPrecRecIMaximals(unsupSumm)

,0,1,2,3,4,5,6,7,8,9,10,11
0,text_7_props,19k_class_childPar,2,True,1,0.433333,0.468750,0.035417,0.325000,0.340909,0.65,0.75
1,text_2_props,19k_2,2,True,3,0.393443,0.430769,0.037327,0.295455,0.311111,0.65,0.70
2,complex,19k_class_childPar,1,True,3,0.620690,0.727273,0.106583,0.916667,0.923077,0.55,0.60
3,transe,19k_childPar,1,True,2,0.600000,0.756757,0.156757,0.846154,0.823529,0.55,0.70
4,abstract,19k_class_childPar,2,True,1,0.521739,0.576923,0.055184,0.461538,0.468750,0.60,0.75
5,abstract_first_sent,19k_childPar,2,True,3,0.523810,0.627451,0.103641,0.466667,0.516129,0.70,0.80

In [47]:
def findPrecRecUMaximals(df):
    embDict = {}
    for _, row in df.iterrows():
        emb = row['Embedding']
        basis = row['Basis']
        newAcc = row['New U F1-Score']
        oldAcc = row['Old U F1-Score']
        iteration = row['Iteration Num']
        if emb not in embDict:
            embDict[emb] = {'maxNewAcc': newAcc, 'maxRow': row, 'oldAcc': -1}
        else:
            if newAcc > embDict[emb]['maxNewAcc'] or (newAcc == embDict[emb]['maxNewAcc'] and 'class' in basis):
                embDict[emb] = {'maxNewAcc': newAcc, 'maxRow': row, 'oldAcc': embDict[emb]['oldAcc']}
        if iteration == 1:
            embDict[emb]['oldAcc'] = oldAcc
    finalRows = []
    for emb in embDict:
        finalRows.append([*embDict[emb]['maxRow'].to_list()[:5], embDict[emb]['oldAcc'], embDict[emb]['maxRow']['New U F1-Score'], embDict[emb]['maxRow']['New U F1-Score'] - embDict[emb]['oldAcc'], embDict[emb]['maxRow']['Old U Precision'], embDict[emb]['maxRow']['New U Precision'], embDict[emb]['maxRow']['Old U Recall'], embDict[emb]['maxRow']['New U Recall'], ])
    return pd.DataFrame(finalRows)

In [48]:
unsupSumm = pd.read_csv('../data/retrofitting/retro_test_Sept_21_2021.csv')
findPrecRecUMaximals(unsupSumm)

,0,1,2,3,4,5,6,7,8,9,10,11
0,text_7_props,19k_2_class,2,True,3,0.065574,0.065574,0.000000,0.210526,0.210526,0.038835,0.038835
1,text_2_props,19k_2_class,2,True,1,0.065574,0.065574,0.000000,0.210526,0.210526,0.038835,0.038835
2,complex,19k_childPar,2,True,2,0.536232,0.542636,0.006404,0.438272,0.451613,0.689320,0.679612
3,transe,19k_2_class,2,True,3,0.366667,0.379310,0.012644,0.434211,0.464789,0.320388,0.320388
4,abstract,19k_2_class,2,True,2,0.089286,0.090909,0.001623,0.625000,0.714286,0.048544,0.048544
5,abstract_first_sent,19k_class_siblings,2,True,2,0.155172,0.123894,-0.031279,0.700000,0.700000,0.067961,0.067961

In [39]:
concatSumm = pd.read_csv('../data/retrofitting/retro_concat_Sep_21_2021.csv')
findMaximals(concatSumm)

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,text_7-text_2-comp-tran-abs-abs_first,19k_2_class,2,True,2,62.5,62.5,0.0,344,0.416667,...,0.416667,0.75,0.535714,0.5,0.029126,0.055046,473.402399,0,63.081395,-0.581395

In [49]:
concatSumm = pd.read_csv('../data/retrofitting/retro_WikiCS_Sep_27_2021.csv')
findMaximals(concatSumm)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,text_7_props,19k_class_siblings,2,True,1,76.334893,73.079537,-3.255356,50837,NaN,...,NaN,NaN,0.378092,0.405654,0.768794,0.735391,129.360480,0,76.334893,-3.255356
1,text_2_props,19k_class_siblings,2,True,1,76.464910,73.318887,-3.146023,50837,NaN,...,NaN,NaN,0.344876,0.373852,0.770582,0.738268,131.612632,0,76.464910,-3.146023
2,complex,19k_class_siblings,2,True,1,92.938685,92.425511,-0.513174,50666,NaN,...,NaN,NaN,0.062191,0.066431,0.941644,0.936380,104.645769,0,92.938685,-0.513174
3,transe,19k_class_siblings,2,True,1,92.014775,89.904950,-2.109825,50666,NaN,...,NaN,NaN,0.131449,0.146290,0.931296,0.909689,100.077391,0,92.014775,-2.109825
4,abstract,19k_class_siblings,2,True,1,93.098252,91.391283,-1.706969,20695,NaN,...,NaN,NaN,0.071378,0.077739,0.943133,0.925732,42.654327,0,93.098252,-1.706969
5,abstract_first_sent,19k_class_siblings,2,True,1,94.562916,93.337602,-1.225314,20695,NaN,...,NaN,NaN,0.065018,0.069258,0.958076,0.945590,42.566209,0,94.562916,-1.225314

In [52]:
concatSumm = pd.read_csv('../data/retrofitting/retro_conceptNet_Sep_27_2021.csv')
findMaximals(concatSumm)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,text_7_props,19k_2_class,1,True,1,18.991529,19.007664,0.016136,599,NaN,...,NaN,NaN,0.984828,0.985747,0.020744,0.020744,45.268861,0,18.991529,0.016136
1,text_2_props,19k_2_class,2,True,3,18.991529,19.007664,0.016136,599,NaN,...,NaN,NaN,0.984828,0.985747,0.020744,0.020744,281.146679,0,18.991529,0.016136
2,complex,19k_2,1,True,3,81.661960,81.920129,0.258169,595,NaN,...,NaN,NaN,0.092874,0.092874,0.970646,0.973777,152.884296,0,81.339250,0.580879
3,transe,19k_2,1,True,3,82.412263,82.476805,0.064542,595,NaN,...,NaN,NaN,0.092874,0.093793,0.979746,0.980333,152.751550,0,82.129891,0.346914
4,abstract,19k_2_class,2,True,3,18.112142,18.112142,0.000000,297,NaN,...,NaN,NaN,0.991724,0.991724,0.008611,0.008611,72.580956,1,18.112142,0.000000
5,abstract_first_sent,19k_2_class,2,True,3,18.104074,18.112142,0.008068,297,NaN,...,NaN,NaN,0.991724,0.991724,0.008513,0.008611,71.931216,0,18.087939,0.024203

In [23]:
def findSVMMaximals(df):
    embDict = {}
    for _, row in df.iterrows():
        emb = row['emb']
        basis = row['basis']
        acc = row['Acc']
        iteration = row['iteration']
        if iteration == 0:
            if emb not in embDict:
                embDict[emb] = {'maxNewAcc': -1, 'maxRow': row, 'oldAcc': acc}
            else:
                embDict[emb] = {'maxNewAcc': embDict[emb]['maxNewAcc'], 'maxRow': embDict[emb]['maxRow'], 'oldAcc': acc}
        else:
            if emb not in embDict:
                embDict[emb] = {'maxNewAcc': acc, 'maxRow': row, 'oldAcc': -1}
            else:
                if acc > embDict[emb]['maxNewAcc'] or (acc == embDict[emb]['maxNewAcc'] and 'class' in basis):
                    embDict[emb] = {'maxNewAcc': acc, 'maxRow': row, 'oldAcc': embDict[emb]['oldAcc']}
    finalRows = []
    for emb in embDict:
        finalRows.append([*embDict[emb]['maxRow'].to_list(), embDict[emb]['oldAcc'], embDict[emb]['maxRow']['Acc'] - embDict[emb]['oldAcc']])
    return pd.DataFrame(finalRows)

In [24]:
svmSumm = pd.read_csv('../data/retrofitting/retro_SVM_Reg_test_Sept_21_2021.csv')
findSVMMaximals(svmSumm)

,0,1,2,3,4,5,6,7,8,9
0,text_7_props_19k_class_childPar_1_weighted,19k_class_childPar,text_7_props,True,2,1,score,0.694370,0.680000,0.014370
1,text_2_props_19k_class_childPar_2_weighted,19k_class_childPar,text_2_props,True,2,2,score,0.694622,0.677311,0.017311
2,complex_19k_2_class_2_weighted,19k_2_class,complex,True,2,2,score,0.668487,0.674538,-0.006050
3,transe_19k_2_class_1_weighted,19k_2_class,transe,True,2,1,score,0.668403,0.674454,-0.006050
4,abstract_19k_class_siblings_2_weighted,19k_class_siblings,abstract,True,2,2,score,0.712017,0.683193,0.028824
5,abstract_first_sent_19k_2_2_weighted,19k_2,abstract_first_sent,True,1,2,score,0.711681,0.714622,-0.002941

In [30]:
def findSVMCombMaximals(df):
    embDict = {}
    for _, row in df.iterrows():
        emb = row['emb_comb']
        basis = row['basis']
        acc = row['accuracy']
        iteration = row['iteration']
        if iteration == 0:
            if emb not in embDict:
                embDict[emb] = {'maxNewAcc': -1, 'maxRow': row, 'oldAcc': acc}
            else:
                embDict[emb] = {'maxNewAcc': embDict[emb]['maxNewAcc'], 'maxRow': embDict[emb]['maxRow'], 'oldAcc': acc}
        else:
            if emb not in embDict:
                embDict[emb] = {'maxNewAcc': acc, 'maxRow': row, 'oldAcc': -1}
            else:
                if acc > embDict[emb]['maxNewAcc'] or (acc == embDict[emb]['maxNewAcc'] and 'class' in basis):
                    embDict[emb] = {'maxNewAcc': acc, 'maxRow': row, 'oldAcc': embDict[emb]['oldAcc']}
    finalRows = []
    for emb in embDict:
        finalRows.append([*embDict[emb]['maxRow'].to_list(), embDict[emb]['oldAcc'], embDict[emb]['maxRow']['accuracy'] - embDict[emb]['oldAcc']])
    return pd.DataFrame(finalRows)

In [36]:
svmCombSumm = pd.read_csv('../data/retrofitting/retro_SVM_Reg_comb_test_Sept_21_2021.csv')
findSVMCombMaximals(svmCombSumm).sort_values(by=[7], ascending=False)

,0,1,2,3,4,5,6,7,8,9
14,abstract_first_sent_19k_2_2_weighted,19k_2,text_2_props & abstract_first_sent,True,1,2,score,0.726555,0.717815,0.008739
37,abstract_19k_class_siblings_2_weighted,19k_class_siblings,complex & transe & abstract,True,3,2,score,0.726303,0.679916,0.046387
44,abstract_19k_2_class_1_weighted,19k_2_class,text_7_props & text_2_props & transe & abstract,True,3,1,score,0.724034,0.697395,0.026639
45,abstract_first_sent_19k_class_childPar_2_weighted,19k_class_childPar,text_7_props & text_2_props & transe & abstrac...,True,3,2,score,0.721092,0.714790,0.006303
49,abstract_first_sent_19k_childPar_1_weighted,19k_childPar,text_7_props & complex & abstract & abstract_f...,True,1,1,score,0.720924,0.665294,0.055630
...,...,...,...,...,...,...,...,...,...,...
6,text_2_props_19k_class_childPar_1_weighted,19k_class_childPar,text_7_props & text_2_props,True,3,1,score,0.694370,0.674286,0.020084
20,abstract_first_sent_19k_class_siblings_2_weighted,19k_class_siblings,abstract & abstract_first_sent,True,3,2,score,0.691429,0.682857,0.008571
15,transe_19k_siblings_2_weighted,19k_siblings,complex & transe,True,1,2,score,0.668655,0.662689,0.005966
2,complex_19k_2_class_2_weighted,19k_2_class,complex,True,3,2,score,0.668487,0.674538,-0.006050
3,transe_19k_2_class_1_weighted,19k_2_class,transe,True,3,1,score,0.668403,0.674454,-0.006050