In [1]:
import pandas as pd

In [2]:
wordSim353AnnotDF_New_Merged_DF = pd.read_csv('../data/wordsim353_all_embeddings_with_retrofits.csv')

In [7]:
wordSim353AnnotDF_New_Merged_DF.head()

,Word 1,Word 2,ID,H_Sim,H_Dim,F_Sim,F_Dim,N_Sim,N_Dim,D_Sim,...,concat_19k_v2_word1_new,concat_19k_v2_word2_new,concat_19k_v2_old_cosSim,concat_19k_v2_2_new_cosSim,concat_probase_19k_v2_word1_old,concat_probase_19k_v2_word2_old,concat_probase_19k_v2_word1_new,concat_probase_19k_v2_word2_new,concat_probase_19k_v2_old_cosSim,concat_probase_19k_v2_2_new_cosSim
0,Arafat,peace,8,3,D,4,NaN,3,U,4,...,"[0.006720443092017323, 0.008331487679612525, 0...","[-0.004515859576248157, -0.01172366887295375, ...",3.244539,3.175157,"[0.006720440291834372, 0.008331484208161396, 0...","[-0.005011610937734838, -0.013383541550578623,...","[0.006720440291834372, 0.008331484208161396, 0...","[-0.00497129831746384, -0.01325426749683971, -...",3.244539,3.240270
1,Arafat,terror,9,3,D,4,NaN,3,U,4,...,"[0.006720443092017323, 0.008331487679612525, 0...","[-0.004862257088069111, 0.014077170590128979, ...",3.085083,3.013958,"[0.006720440291834372, 0.008331484208161396, 0...","[-0.005805280438126139, 0.015115419696749257, ...","[0.006720440291834372, 0.008331484208161396, 0...","[-0.004862255062129871, 0.014077164724644747, ...",3.085083,3.013958
2,FBI,fingerprint,109,3,D,4,NaN,4,NaN,3,...,"[0.006466897059812569, 0.014694837542908411, -...","[0.01523113309590259, 0.005271417380511587, -0...",2.823093,2.745230,"[0.006466894365273728, 0.014694831420063071, -...","[0.013922101136130544, 0.0023911842131386003, ...","[0.006466894365273728, 0.014694831420063071, -...","[0.013814564227839972, 0.0024352598952305004, ...",2.823093,2.816176
3,FBI,investigation,110,3,U,3,U,3,U,3,...,"[0.006466897059812569, 0.014694837542908411, -...","[0.013016090623183913, 0.01114268771757639, -0...",2.920986,2.886161,"[0.006466894365273728, 0.014694831420063071, -...","[0.01327496060589727, 0.010965634890657862, -0...","[0.006466894365273728, 0.014694831420063071, -...","[0.013242882546106787, 0.010953106196386554, -...",2.920986,2.919120
4,Harvard,Yale,137,2,S,3,S,2,S,2,...,"[0.01322626159341165, 0.005047111630696947, -0...","[0.010410829393995813, 0.014776997996557633, -...",1.707655,1.707655,"[0.013226256082472592, 0.005047109527735016, -...","[0.010410825056152807, 0.014776991839478788, -...","[0.013226256082472592, 0.005047109527735016, -...","[0.010410825056152807, 0.014776991839478788, -...",1.707655,1.707655

In [4]:
wordSim353AnnotDF_New = pd.read_csv('../data/wordsim353LatestAnnot.csv')
wordSimOG_DF = pd.read_csv('../data/wordsim.csv')

In [5]:
wordSim353AnnotDF_New = wordSim353AnnotDF_New.set_index(['Word 1', 'Word 2']).join(wordSimOG_DF.set_index(['Word 1', 'Word 2'])[['word1_kg_id', 'word2_kg_id']]).reset_index()

In [6]:
wordSim353AnnotDF_New.head()

,Word 1,Word 2,ID,H_Sim,H_Dim,F_Sim,F_Dim,N_Sim,N_Dim,D_Sim,D_Dim,P_Sim,P_Dim,Avg,Stdev,H_orig,H_reversed,word1_kg_id,word2_kg_id
0,Arafat,peace,8,3,D,4,NaN,3,U,4,NaN,4.0,NaN,3.6,0.547723,2.1250,7.8750,Q34211,Q454
1,Arafat,terror,9,3,D,4,NaN,3,U,4,NaN,4.0,NaN,3.6,0.547723,3.0625,6.9375,Q34211,Q13648784
2,FBI,fingerprint,109,3,D,4,NaN,4,NaN,3,u,4.0,NaN,3.6,0.547723,4.0625,5.9375,Q8333,Q178022
3,FBI,investigation,110,3,U,3,U,3,U,3,u,3.0,u,3.0,0.000000,5.0625,4.9375,Q8333,Q21004260
4,Harvard,Yale,137,2,S,3,S,2,S,2,s,2.0,s,2.2,0.447214,4.8750,5.1250,Q13371,Q49112

In [9]:
wordSim353AnnotDF_New_Merged_DF

0      3.60
1      3.60
2      3.60
3      3.00
4      2.20
       ...
339    3.00
340    3.80
341    3.00
342    1.80
343    3.75
Name: Avg, Length: 344, dtype: float64

In [13]:
wordSim353AnnotDF_New = wordSim353AnnotDF_New[['word1_kg_id', 'word2_kg_id', 'Avg']]
temp1 = wordSim353AnnotDF_New_Merged_DF.set_index(['word1_kg_id', 'word2_kg_id']).join(wordSim353AnnotDF_New.set_index(['word1_kg_id', 'word2_kg_id']), rsuffix="_old").reset_index()

In [18]:
temp2 = temp1[temp1.Avg != temp1.Avg_old][['Avg', 'Avg_old']]

In [19]:
def labelSamples(score):
    return 'I' if score <= 1.75 else 'U' if score >= 3.5 else 'M'

In [22]:
temp2['Cat'] = temp2.Avg.apply(labelSamples)
temp2['Cat_old'] = temp2.Avg_old.apply(labelSamples)
temp2

     Avg  Avg_old Cat Cat_old
33   4.0      3.4   U       M
37   2.2      3.2   M       M
64   3.6      3.2   U       M
65   3.6      3.2   U       M
66   3.0      3.6   M       U
67   3.0      3.6   M       U
68   3.0      3.2   M       M
69   3.0      3.2   M       M
96   2.8      3.4   M       M
128  1.8      2.2   M       M
164  1.8      2.2   M       M
171  2.0      2.4   M       M
185  2.8      3.6   M       U
193  2.8      3.2   M       M
202  1.6      2.4   I       M
238  2.0      2.4   M       M
298  2.2      2.6   M       M
299  1.6      2.2   I       M
336  2.4      3.0   M       M